// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
//
import { defineConfig } from "prisma/config";

// 念のため実行時にログを出して確認（コンテナの起動ログに出ます）
if (!process.env.DATABASE_URL) {
  console.warn("⚠️ [PrismaConfig] DATABASE_URL is NOT found in process.env");
}

export default defineConfig({
  earlyAccess: true, // Prisma 7 で推奨される場合があります
  schema: "prisma/schema.prisma",
});

